version: '3'

services:

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432

  keycloak:
    image: jboss/keycloak
    restart: always
    links:
      - postgres
    ports:
      - "8181:8080"
    environment:
      KEYCLOAK_USER : admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    depends_on:
      - postgres

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411